### ISSUE TITLE
Build kraken in a docker container

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken#174] opened 2017-09-22 23:19 UTC
When we build kraken, the version of go and godep and anything else is all dependent on what's installed on the machine doing to build.

We should do the build in docker using something like library/golang to ensure consistency.

**Comment by alejandroEsc** [comment] 2017-09-23 00:44
sounds good, been thinking about it.

**Comment by alejandroEsc** [comment] 2017-09-28 15:25
Closing, duplicate of https://github.com/samsung-cnct/kraken/issues/128

**Closed by alejandroEsc** 2017-09-28 15:25 UTC
